version: '3.8'

services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - insurance-network

  config-service:
    build: ./config-service
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service
    networks:
      - insurance-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - config-service
    networks:
      - insurance-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888

  auth-service:
    build: ./auth-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
      - config-service
    networks:
      - insurance-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888

  customer-service:
    build: ./customer-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
      - config-service
    networks:
      - insurance-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888

  policy-service:
    build: ./policy-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
      - config-service
      - customer-service
    networks:
      - insurance-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888

networks:
  insurance-network:
    driver: bridge

